### ISSUE TITLE
Installing this extension doubles top bar height

### ISSUE THREAD

**Issue by battata** [andr3slelouch/Optimus-Manager-Indicator#1]
Hello, I have an issue with the height.
When I install the extension the top bar almost doubles its height, pushing UI elements further down and getting in the way of normal windows UI.
Also, the icon is always 3 dots
Thanks

Without extension:
![Captura de pantalla de 2020-04-20 08-13-40](https://user-images.githubusercontent.com/24719702/79745560-ebe18f00-82de-11ea-8a93-518b1f7bd2d6.png)

With extension:
![Captura de pantalla de 2020-04-20 08-06-34](https://user-images.githubusercontent.com/24719702/79745389-8ee5d900-82de-11ea-96a4-0dd364af7729.png)

**Comment by andr3slelouch** [comment]
Hello, the Intel icon it is showed on the top bar? If not, maybe the icons are not on the correspondingly directory.
You can check in the ~/.local/share/gnome-shell/extensions/optimus-manager-indicator@andr3slelouch.github.com/ directory if they exists.
Another option can be download and replace the extension.js file with the one from this repository.

**Comment by canalocaradoti** [comment]
I'm also having the same problem, I'm on Ubuntu 20.04. The icons are in the folder mentioned and already replaces the file extension.js and continues the same thing =/

**Comment by andr3slelouch** [comment]
I just noticed and the error occurs because this extension uses optimus-manager to work and is only available for arch-based distributions, sorry, maybe in the future I can create an extension for ubuntu, my apologies.
