### ISSUE TITLE
Change distro identification procedure

### ISSUE THREAD

**Issue by sanyer** [andr3slelouch/Optimus-Manager-Indicator#12]
Hi!
Thanks for this simple and yet effective extension.
I'm using Manjaro and while extension works, its settings are not available.
Apparently, because of the internal error.
In code I see that you determine distro by parsing `/etc/issue.net`. And this file doesn't exist in Manjaro.

Perhaps it would make a bit more sense to use `/etc/os-release` for this purpose.

Could do something like this:
```sh
awk -F= '$1=="ID" { print $2 ;}' /etc/os-release
```

**Comment by andr3slelouch** [comment]
Nice, it wasn't implemented for that doubt about detecting the correct distro name, i will try to implement as soon as possible.
Thank you a lot for your contribution.
