### ISSUE TITLE
optimus-manager intel mode name

### ISSUE THREAD

**Issue by sanyer** [andr3slelouch/Optimus-Manager-Indicator#13]
Extension is using this command get current mode:
```sh
optimus-manager --print-mode | grep 'Current GPU mode' | awk '{print $5}'
```

And `_setMenuMode` expects either 'inter', 'nvidia' or 'hybrid'.
`optimus-manager` returns `integrated` instead of `intel` for me and because of this error message `You're not using GDM-PRIME` keeps popping up on every start.

**Comment by andr3slelouch** [comment]
Hello!  I realized that and it was corrected, it would be ready in the next Release.
Thanks for your contribution.
