### ISSUE TITLE
Preference don't work

### ISSUE THREAD

**Issue by sanyer** [andr3slelouch/Optimus-Manager-Indicator#14]
Manjaro Linux 21.0.1, Gnome 40

When I try to open settings I see error screen:
```
Something's gone wrong

We're very sorry, but there's been a problem: the settings for extension can't be displayed...
```
And nothing more.
I wasn't able to find anything in logs.

**Comment by andr3slelouch** [comment]
Ohhhhh i need to enable compatibility with gnome 3.38, i have forgot it. I'm going to try. My apologies.

**Comment by andr3slelouch** [comment]
Hey can you try it with the prerelease 1.5b? https://github.com/andr3slelouch/Optimus-Manager-Indicator/releases/tag/v1.5b

**Comment by sanyer** [comment]
this worked, thanks :-)

**Comment by andr3slelouch** [comment]
Nice
