### ISSUE TITLE
Extension Prompt Stuck

### ISSUE THREAD

**Issue by coltonhughes** [andr3slelouch/Optimus-Manager-Indicator#17]
The tray icon pops up that it needs to restart, but clicking yes does not close the prompt nor does it restart the x server.
 System Info:
 ```
OS: Manjaro 21.0.2 Ornara
 Kernel: x86_64 Linux 5.10.30-1-MANJARO
 Uptime: 16m
 Packages: 1231
 Shell: zsh 5.8
 Resolution: 1920x1080
 DE: GNOME 3.38.5
 WM: Mutter
 WM Theme: Matcha-dark-sea
 GTK Theme: Matcha-sea [GTK2/3]
 Icon Theme: Papirus-Dark-Maia
 Font: Noto Sans 11
 Disk: 38G / 946G (5%)
 CPU: Intel Core i7-9750H @ 12x 4.5GHz [49.0°C]
 GPU: GeForce GTX 1650
 RAM: 1799MiB / 15637MiB

```

**Comment by andr3slelouch** [comment]
Im so sorry. i have review it and the new implementation breaks the extension for Manjaro users i would try to solve it as soon as possible. My apologies. I have just inactivated that version please use 5(v1.4 here in github) version

**Comment by coltonhughes** [comment]
No problem. Thanks for the response.
Colton Hughes
***@***.***
