### ISSUE TITLE
Testing for version v2b

### ISSUE THREAD

**Issue by andr3slelouch** [andr3slelouch/Optimus-Manager-Indicator#19]
Hello everyone I need you for testing, before posting the new version to the Gnome Extensions Store I don't want to post it with errors like the last time...
Please install https://github.com/andr3slelouch/Optimus-Manager-Indicator/releases/tag/v2b and tell me if you find some errors or issue.
@coltonhughes @sanyer @ViBE-HU @rodolpheh
I thank you in advance.

**Comment by ViBE-HU** [comment]
I noticed the following issues:

1. When I want to switch to other GPU and the authentication is done nothing happens. X server does not restarts. But it changes GPU after manual restarts.
2. Hybrid mode cause me a **kernel panic**, so I'm actually stuck atm...

I can provide details later. The system is Ubuntu 20.04 x64. Btw I would do the Hungarian translation so I will correct the file and share it soon.

**Comment by ViBE-HU** [comment]
Gladly I can boot up with an older kernel and change back the settings. Do you need some exact log files? The plugin settings does not work btw.

**Comment by andr3slelouch** [comment]
> I noticed the following issues:
> 
>     1. When I want to switch to other GPU and the authentication is done nothing happens. X server does not restarts. But it changes GPU after manual restarts.
> 
>     2. Hybrid mode cause me a **kernel panic**, so I'm actually stuck atm...
> 
> 
> I can provide details later. The system is Ubuntu 20.04 x64. Btw I would do the Hungarian translation so I will correct the file and share it soon.

All right all right thats something i wanted to know, and if you can give some details would be better for implementing the plugin for Ubuntu.

**Comment by andr3slelouch** [comment]
> Gladly I can boot up with an older kernel and change back the settings. Do you need some exact log files? The plugin settings does not work btw.

Really? what it says when you try to go to preferences? it gives you a error or something? let me see

**Comment by andr3slelouch** [comment]
> I would do the Hungarian translation so I will correct the file and share it soon.

Nice because i was using Google Translator and i wasnt sure about that translations xD

**Comment by NGStaph** [comment]
something similar happens on arch as well, using the optimus-manager command logs me out and switches GPU but the gnome extension does not work.

**Comment by andr3slelouch** [comment]
Wait really? Even in arch is not working? Can you try this version? https://github.com/andr3slelouch/Optimus-Manager-Indicator/releases/tag/v2b2

**Comment by NGStaph** [comment]
sorry, i opted for the only nvidia route. I'm also getting micro-stutters every ~2 seconds using optimus-manager

**Comment by andr3slelouch** [comment]
> sorry, i opted for the only nvidia route. I'm also getting micro-stutters every ~2 seconds using optimus-manager
Do not worry. Thanks for the reply. (I also have that problem, but it comes and goes with each update)

**Comment by NGStaph** [comment]
heh. i switched to optimus-manager again. your extension (linked above) works fine!
this time, no matter what i switch to the stutters remain and the mode is always hybrid!
reverting to nvidia only.

**Comment by andr3slelouch** [comment]
> heh. i switched to optimus-manager again. your extension (linked above) works fine!
> this time, no matter what i switch to the stutters remain and the mode is always hybrid!
> reverting to nvidia only.

Thanks for the testing and yes the stuttering ruins the user experience.
