### ISSUE TITLE
[Feature request][Probably redundant] Add hybrid mode

### ISSUE THREAD

**Issue by rodolpheh** [andr3slelouch/Optimus-Manager-Indicator#2]
I love that you took the time to develop an alternative to the now defunct Argos-based optimus-manager extension. Would you consider adding the hybrid mode in the list ? I was responsible for adding it in the previous Argos-based extension, I could probably take some time to look into integrating it in your extension.

Thank you in advance

**Comment by rodolpheh** [comment]
Well I just looked into your code and it seems that you already planned that. If this is the case and I just need to wait for the Gnome Extensions website to pick up the latest version, please close this issue.

EDIT: looking again, I may have misunderstood how the extension works. Does it hide the current mode ? This would explain why I don't see hybrid mode. Sorry for this useless request.

**Comment by andr3slelouch** [comment]
Yeah it's the way that it works, but it seems to be confusing xD, maybe in the next version I'm gonna only put the option unclickable. 
I'm closing this issue, if you have another questions or something, please open another, I will be happy to help you.
