### ISSUE TITLE
Gnome 40 incompatable

### ISSUE THREAD

**Issue by Yabbo** [andr3slelouch/Optimus-Manager-Indicator#21]
When i go to the Gnome extension on gnome 40 it shows as incomparable.

**Comment by jgalec** [comment]
You need to change "40.0" to "40" in metadata.json (This worked for me)

**Comment by andr3slelouch** [comment]
Really? Why? i dont understand but it was working for me but try it for the moment @Yabbo. i will release a new version to the store in a couple of days and i will change that

**Comment by ghost** [comment]
You need to change "40.0" to "40" in metadata.json in the "shell-version" line (This worked for me)

**Comment by andr3slelouch** [comment]
> You need to change "40.0" to "40" in metadata.json in the "shell-version" line (This worked for me)

Thanks

**Comment by DogInSpaace** [comment]
Unfortunately this still shows as incompatible with gnome 40 https://extensions.gnome.org/extension/2908/optimus-manager-indicator/

**Comment by developomp** [comment]
> You need to change "40.0" to "40" in metadata.json in the "shell-version" line (This worked for me)

Someone change the required gnome version lmao. I'm on 40.5 and have to resort to hacks whenever I install it.
