### ISSUE TITLE
Does not work on Gnome 41

### ISSUE THREAD

**Issue by NGStaph** [andr3slelouch/Optimus-Manager-Indicator#28]
please add support for gnome 41.

**Comment by JustCryen** [comment]
It is actually working but the version is not bumped up.
You can do it manually and edit the `metadata.json` in `~/.local/share/gnome-shell/extensions/<extension-folder>` and add "41" to the end of `"shell-version"` line.
Just keep in mind to preserve the correct separation with commas and brackets.

**Comment by lmtr0** [comment]
I setted that up, however when I try enabling it, it gives this error:
![image](https://user-images.githubusercontent.com/57605930/149260367-04acca3a-0a26-4f87-9bfd-770165150da5.png)

**Comment by JustCryen** [comment]
What's the directory structure in `~/.local/share/gnome-shell/extensions/optimus-manager-indicator@andr3slelouch.github.com`?
it should have the main extension files directly in it, no unnecessary folders / layers.
File content: icons  schemas  *extension.js*  *LICENSE*  *metadata.json*  *prefs.js*

**Comment by lmtr0** [comment]
yeah. and the extensions application tells me that the extension is not compatible with this shell, even when I put the version 41

**Comment by NGStaph** [comment]
dunno why you're mv'ing the folder, you could simply... 

1. download the 40.0 v5 pkg from gnome extensions website 
2. cd to "Downloads" 
3. 'gnome-extensions install _downloaded-package_' 
4. follow @JustCryen 's steps (modify metadata.json file at aforementioned path)
5. reboot and enable the extension

**Comment by JustCryen** [comment]
Weird, maybe you forgot a comma or something.
I also downloaded it from gnome extensions website but I did move it by hand.

That's how I have my shell version set in metadata.json
```
"shell-version": [
    "3.36",
    "3.38",
    "40.0",
    "41"
  ],
  ```
Also, I assume you tried restarting your pc or at least logging off and back on.
On xorg you can just `alt` + `f2` -> `r` to reload gnome.
And yeah, I'm not sure if this extension works on wayland.

Edit:
One more thing, I just released that the enable command might not mean that's how the extension folder is named.
It might as well read the uuid section from metadata.json
Be sure you have the @ symbol in the folder name.
I had to add it myself.

**Comment by lmtr0** [comment]
Ok, it worked now
thanks
