### ISSUE TITLE
Missing panel icon

### ISSUE THREAD

**Issue by ViBE-HU** [andr3slelouch/Optimus-Manager-Indicator#3]
I'm on Ubuntu 20.04 and i only see the placeholder I guess.

![Képernyőkép erről: 2020-10-02 23-28-21](https://user-images.githubusercontent.com/640109/94971451-5857ef80-0507-11eb-9a5d-db34c0bc2695.png)

**Comment by platypusgit** [comment]
Same here on Manjaro Gnome. At Startup there is the usual Icon (Intel in my case), but after a short period of time it is not visible anymore.

**Comment by andr3slelouch** [comment]
Hi @ViBE-HU this extension was made for Arch based distros but, I will try to adapt it for Ubuntu, I will not guarantee anything but I will try :3.

**Comment by ViBE-HU** [comment]
Oh, okay. Thanks for your work @andr3slelouch. Btw it's strange that even Manjaro have a problem with the extention then.

**Comment by andr3slelouch** [comment]
> Same here on Manjaro Gnome. At Startup there is the usual Icon (Intel in my case), but after a short period of time it is not visible anymore.

Hi, Optimus-Manager has trouble with gdm-prime after suspend the system or restart the shell. I made a update for show the intel indicator at least(but without functionality) but i have not uploaded it yet, I think i will do it in some hours.

**Comment by andr3slelouch** [comment]
> Oh, okay. Thanks for your work @andr3slelouch. Btw it's strange that even Manjaro have a problem with the extention then.

You are welcome. I'm happy for the interest on it.
The problem born with a patched version of gdm that gives some trouble after a suspend or restart of the shell.

**Comment by andr3slelouch** [comment]
@platypusgit I have upload the update can you try it? It is available on https://extensions.gnome.org/extension/2908/optimus-manager-indicator/

**Comment by platypusgit** [comment]
@andr3slelouch I just checked: With the new update the icon is showing after a suspend/restart of the shell. I also get a notification for a split-second, that gdm-prime is not installed or not working(?). This might be because of the patched version of gdm-prime you mentioned - so we'll have to wait for them to push an update, I guess.

Thank you very much!

**Comment by andr3slelouch** [comment]
You are welcome, right now I'm trying to add a forced mode to always show gpu temperature, wait for the update, greetings for everyone.
