### ISSUE TITLE
[Feature request] Display the actually active card's icon

### ISSUE THREAD

**Issue by ViBE-HU** [andr3slelouch/Optimus-Manager-Indicator#5]
On Windows Optimus systems has an additional indicator icon which tells you if the nVidia card is actually the main card and an application is actually using it. It's a bit unnecessary but it would be good on Linux if the indicator icon could show the exact active card's icon. I'm using hybrid mode and it's always shows just the nVidia and never Intel sadly while it's absolutely clear that Intel is the primary card.

**Comment by andr3slelouch** [comment]
First sorry for answer after so long time and second i don't have any idea of how to do that, I will try to do some research, I understand that in hybrid mode when you are using the gpu nvidia icons shows and when it is using Intel shows that, is that right?

**Comment by andr3slelouch** [comment]
Hey @ViBE-HU i figured out that i can get some information about the gpu using nvida-smi so i will put the intel icon only if gpu and memory stats are in 0%, what do you think? 
![image](https://user-images.githubusercontent.com/45749416/114819255-ce74c300-9d82-11eb-8af2-6c60cf990df6.png)

**Comment by ViBE-HU** [comment]
Oh. I didn't noticed this. I have no idea sadly cause I'm not into programming. But I guess the grep based solution can work. Thanks.

**Comment by andr3slelouch** [comment]
It doesn't matters i will try to do some test and see if that is correct apparently it is, because applications like nvtop not shows any graphs with gpu and memory in 0%, but when im in nvidia mode the nvtop has a lot of graphs because the gpu is being used, that is, gpu and memory with values greater that 0%.

**Comment by andr3slelouch** [comment]
Done in https://github.com/andr3slelouch/Optimus-Manager-Indicator/commit/d688c407988f058887bf01bd863b1742b124c335
