### ISSUE TITLE
[Feature request] Language support

### ISSUE THREAD

**Issue by ViBE-HU** [andr3slelouch/Optimus-Manager-Indicator#6]
I know this is a very straight forward stuff but it would be nice. Are there any chances?

**Comment by andr3slelouch** [comment]
Well i have never tried, what languages do you suggest?

**Comment by ViBE-HU** [comment]
Basically any what users request/would translate. In my case Hungarian.

**Comment by andr3slelouch** [comment]
Okay, I'll prepare it for translations and give it a try, but it will take a while.
