### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by Xiphity** [andr3slelouch/Optimus-Manager-Indicator#7]
Please add gnome 40 support to this extension.

**Comment by andr3slelouch** [comment]
Hello, im a little busy but i will try to do it as soon as possible (I need it too xD).

**Comment by Xiphity** [comment]
Thanks!

**Comment by andr3slelouch** [comment]
https://github.com/andr3slelouch/Optimus-Manager-Indicator/releases/tag/v1.4 Hey you can try it

**Comment by Xiphity** [comment]
It's work fine now.
Thanks!
